pre-release-replacements = [
  {file="CHANGELOG.md", search="Unreleased", replace="{{version}}"},
  {file="CHANGELOG.md", search="\\.\\.\\.HEAD", replace="...{{tag_name}}", exactly=1},
  {file="CHANGELOG.md", search="ReleaseDate", replace="{{date}}"},
  {file="CHANGELOG.md", search="<!-- next-header -->", replace="<!-- next-header -->\n\n## [Unreleased] - ReleaseDate", exactly=1},
  {file="CHANGELOG.md", search="<!-- next-url -->", replace="<!-- next-url -->\n[Unreleased]: https://github.com/cgm616/wordle_rs/compare/{{tag_name}}...HEAD", exactly=1},
  {file="README.md", search="wordle_rs = *", replace="{{crate_name}} = \"{{version}}\""},
  {file="README.md", search="wordle_strategies = *", replace="wordle_strategies = \"{{version}}\""},
]
sign-commit = true
sign-tag = true
push-remote = "github"
allow-branch = ["master"]
consolidate-commits = true
consolidate-pushes = true
shared-version = true