[package]
name = "wordle_strategies"
version = "0.1.0-dev"
edition = "2021"

[dependencies]
itertools = "0.10"
lazy_static = "1.4"
regex = "1.5"
wordle_perf = { path = "../wordle_perf", version = "0.1.0-dev" }
