[package]
name = "wordle_perf"
version = "0.1.0-dev"
edition = "2021"

[dependencies]
comfy-table = "5.0"
indicatif = {version = "0.16", features = ["rayon"]}
itertools = "0.10.3"
rand = "0.8"
rayon = "1.5.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
