[package]
name = "wordle_runner"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wordle_strategies = {version = "0.1", path = "../wordle_strategies"}
wordle_rs = {version = "0.1", path = "../"}
