pre-release-replacements = [
  {file="README.md", search="wordle_rs = *", replace="wordle_rs = \"{{version}}\""},
  {file="README.md", search="wordle_strategies = *", replace="wordle_strategies = \"{{version}}\""},
  {file="README.md", search="wordle_runner = *", replace="{{crate_name}} = \"{{version}}\""},
]
release = false
tag = false
shared-version = true